eval "$(starship init zsh)"

export PATH="$(brew --prefix)/bin:$(brew --prefix)/homebrew/sbin:$PATH"

alias gcc=$(brew --prefix gcc)/bin/gcc-14
alias g++=$(brew --prefix gcc)/bin/g++-14
alias ar=$(brew --prefix binutils)/bin/ar

export CC=$(brew --prefix gcc)/bin/gcc-14
export CXX=$(brew --prefix gcc)/bin/g++-14
export CPP=$(brew --prefix binutils)/bin/g++-14
export AR=$(brew --prefix binutils)/bin/ar

alias vim="nvim"
alias ctags=$(brew --prefix)/bin/ctags

source ~/.zplug/init.zsh

# plugins
zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug load

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# custom commands
pm() {
    local orig_dir=$(pwd)
    cd ..
    make
    cd "$orig_dir"
}

pc() {
    cmake .. && make
}

