eval "$(starship init zsh)"

export PATH="$(brew --prefix)/bin:/$(brew --prefix)/homebrew/sbin:$PATH"
export PATH="$(brew --prefix binutils)/bin:$PATH"
export PATH="$(brew --prefix llvm)/bin:$PATH"
export PATH="$(brew --prefix)/sbin:$PATH"
export CC='clang'
export CXX='clang++'

alias vim="nvim"
alias ctags=/opt/homebrew/bin/ctags

pm() {
    local orig_dir=$(pwd)
    cd ..
    make
    cd "$orig_dir"
}

pc() {
    cmake .. && make
}
